import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LandingBody from "@/components/LandingBody";

export default function Home() {
  return (
    <>
      <Head>
        <title>Joshua Payne | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LandingBody />
      </main>
    </>
  );
}
